[project]
name = "Midoris-AutoFighter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "halo>=0.0.31",
    "pygame>=2.6.1",
    "snakeviz>=2.2.2",
]
