FROM lunamidori5/pixelarch:emerald

RUN sudo sed -i 's/Emerald/Game Builder/g' /etc/os-release

ARG USERNAME=midori-ai

WORKDIR /game

USER root

RUN echo "[multilib]" >> /etc/pacman.conf
RUN echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf

USER $USERNAME

RUN yay -Syu --noconfirm wine && yay -Yccc --noconfirm

COPY builder.sh .
COPY .. .

RUN sudo chown -R $USERNAME:$USERNAME /game
RUN chmod +x builder.sh
CMD bash builder.sh