FROM lunamidori5/pixelarch:topaz

ENV PYTHONOPTIMIZE=2

RUN sudo sed -i 's/Topaz/Game Builder/g' /etc/os-release

ARG USERNAME=midori-ai

WORKDIR /game

COPY builder.sh .

RUN sudo chown -R $USERNAME:$USERNAME /game
RUN chmod +x builder.sh

CMD bash builder.sh