FROM lunamidori5/pixelarch:topaz

RUN sudo sed -i 's/Topaz/Game Builder/g' /etc/os-release

ARG USERNAME=midori-ai

WORKDIR /game

USER root

RUN echo "[multilib]" >> /etc/pacman.conf
RUN echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf

USER $USERNAME

RUN yay -Syu --noconfirm wine uv xorg-server-xvfb && yay -Yccc --noconfirm

COPY builder.sh .

RUN sudo chown -R $USERNAME:$USERNAME /game
RUN chmod +x builder.sh

CMD bash builder.sh