name: Debian Package Build

on:
  workflow_dispatch:

jobs:
  debian-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Debian package
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper
          cp -r packaging/debian debian
          dpkg-buildpackage -b -us -uc
