name: Flatpak Build

on:
  workflow_dispatch:

jobs:
  flatpak-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Flatpak manifest
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak-builder
          flatpak-builder --user --install --force-clean builddir packaging/flatpak/org.midori.ai.autofighter.yaml
