name: Build Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [non-llm, llm-cpu, llm-cuda, llm-amd]
        
    steps:
      - uses: actions/checkout@v4
      
      - uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'
      
      - name: Install bun
        run: |
          powershell -c "irm bun.sh/install.ps1|iex"
          echo "$env:USERPROFILE\.bun\bin" >> $env:GITHUB_PATH
          
      - name: Setup backend environment
        working-directory: backend
        run: |
          uv sync
          
      - name: Install backend variant dependencies
        working-directory: backend
        run: |
          if ("${{ matrix.variant }}" -eq "llm-cpu") {
            uv sync --extra llm-cpu
          } elseif ("${{ matrix.variant }}" -eq "llm-cuda") {
            uv sync --extra llm-cuda
          } elseif ("${{ matrix.variant }}" -eq "llm-amd") {
            uv sync --extra llm-amd
          }
          
      - name: Install PyInstaller for backend
        working-directory: backend
        run: uv add --dev pyinstaller
        
      - name: Build frontend
        working-directory: frontend
        run: |
          bun install
          bun run build
          
      - name: Build backend executable
        working-directory: backend
        run: |
          # Ensure frontend build directory exists
          if (-not (Test-Path "../frontend/build")) {
            Write-Host "Error: Frontend build directory not found at ../frontend/build"
            Write-Host "Available directories in frontend:"
            Get-ChildItem ../frontend/
            exit 1
          }
          
          $dataArgs = "--add-data ../frontend/build;frontend"
          $cmd = "uv run pyinstaller --onefile $dataArgs --clean --name midori-autofighter-${{ matrix.variant }}-windows app.py"
          Invoke-Expression $cmd
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: midori-autofighter-${{ matrix.variant }}-windows
          path: backend/dist/midori-autofighter-${{ matrix.variant }}-windows.exe
          retention-days: 30