name: Build Android

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Build frontend for mobile
        working-directory: frontend
        run: |
          bun install
          bun run build
          
      - name: Setup mobile build environment
        working-directory: build/mobile
        run: |
          bun install
          
      - name: Build Android APK
        working-directory: build/mobile
        run: |
          # Sync frontend build to Capacitor
          bun run sync
          
          # Build APK
          cd android
          ./gradlew assembleDebug
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: midori-autofighter-non-llm-android
          path: build/mobile/android/app/build/outputs/apk/debug/*.apk
          retention-days: 30