name: AUR Build

on:
  workflow_dispatch:

jobs:
  aur-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build PKGBUILD
        working-directory: packaging/aur
        run: |
          pacman -Sy --noconfirm base-devel git
          useradd -m build
          chown -R build:build .
          su build -c 'makepkg --printsrcinfo'
